/opt/slurm/cluster/raven/spool/gpu108-23-r/slurmd/job200289/slurm_script: line 14: source: /home/khanff/miniconda3/envs/lomar: is a directory
/home/khanff/miniconda3/envs/lomar/lib/python3.6/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/khanff/miniconda3/envs/lomar/bin/python: can't open file 'main_pretrain_lomar.py': [Errno 2] No such file or directory
/home/khanff/miniconda3/envs/lomar/bin/python: can't open file 'main_pretrain_lomar.py': [Errno 2] No such file or directory
/home/khanff/miniconda3/envs/lomar/bin/python: can't open file 'main_pretrain_lomar.py': [Errno 2] No such file or directory
/home/khanff/miniconda3/envs/lomar/bin/python: can't open file 'main_pretrain_lomar.py': [Errno 2] No such file or directory
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 45930) of binary: /home/khanff/miniconda3/envs/lomar/bin/python
Traceback (most recent call last):
  File "/home/khanff/miniconda3/envs/lomar/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/khanff/miniconda3/envs/lomar/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/khanff/miniconda3/envs/lomar/lib/python3.6/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/khanff/miniconda3/envs/lomar/lib/python3.6/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/khanff/miniconda3/envs/lomar/lib/python3.6/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/khanff/miniconda3/envs/lomar/lib/python3.6/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home/khanff/miniconda3/envs/lomar/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/khanff/miniconda3/envs/lomar/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main_pretrain_lomar.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-10-18_15:21:21
  host      : gpu108-23-r.ibex.kaust.edu.sa
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 45931)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2022-10-18_15:21:21
  host      : gpu108-23-r.ibex.kaust.edu.sa
  rank      : 2 (local_rank: 2)
  exitcode  : 2 (pid: 45932)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2022-10-18_15:21:21
  host      : gpu108-23-r.ibex.kaust.edu.sa
  rank      : 3 (local_rank: 3)
  exitcode  : 2 (pid: 45933)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-10-18_15:21:21
  host      : gpu108-23-r.ibex.kaust.edu.sa
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 45930)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
