/home/khanff/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
WARNING:torch.distributed.run:*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
`fused_weight_gradient_mlp_cuda` module not found. gradient accumulation fusion with weight gradient computation disabled.
`fused_weight_gradient_mlp_cuda` module not found. gradient accumulation fusion with weight gradient computation disabled.
`fused_weight_gradient_mlp_cuda` module not found. gradient accumulation fusion with weight gradient computation disabled.
`fused_weight_gradient_mlp_cuda` module not found. gradient accumulation fusion with weight gradient computation disabled.
Traceback (most recent call last):
  File "main_pretrain.py", line 27, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "main_pretrain.py", line 27, in <module>
  File "main_pretrain.py", line 27, in <module>
    assert timm.__version__ == "0.3.2"  # version check
AssertionError
    assert timm.__version__ == "0.3.2"  # version check    
assert timm.__version__ == "0.3.2"  # version check
AssertionErrorAssertionError

Traceback (most recent call last):
  File "main_pretrain.py", line 27, in <module>
    assert timm.__version__ == "0.3.2"  # version check
AssertionError
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 104510) of binary: /home/khanff/miniconda3/bin/python
Traceback (most recent call last):
  File "/home/khanff/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/khanff/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/khanff/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/khanff/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/khanff/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/khanff/miniconda3/lib/python3.7/site-packages/torch/distributed/run.py", line 692, in run
    )(*cmd_args)
  File "/home/khanff/miniconda3/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/khanff/miniconda3/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
        main_pretrain.py FAILED        
=======================================
Root Cause:
[0]:
  time: 2022-09-28_21:53:58
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 104510)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
[1]:
  time: 2022-09-28_21:53:58
  rank: 1 (local_rank: 1)
  exitcode: 1 (pid: 104511)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[2]:
  time: 2022-09-28_21:53:58
  rank: 2 (local_rank: 2)
  exitcode: 1 (pid: 104512)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[3]:
  time: 2022-09-28_21:53:58
  rank: 3 (local_rank: 3)
  exitcode: 1 (pid: 104513)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
***************************************

/opt/slurm/cluster/ibex/spool/gpu211-18/slurmd/job22158670/slurm_script: line 29: --distributed: command not found
